sudo: false

language: node_js

node_js:
  - "7.4.0"

addons:
  # advanced package tool
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - openjdk-7-jdk
    - lib32stdc++6
    - lib32z1
    # by default java 7 in installed.
    - oracle-java8-set-default

env:
  CXX=g++-4.8

install:
  - npm install -g cordova@6.5.0 ionic@2.2.3
  - npm install

before_script:
  - wget http://dl.google.com/android/android-sdk_r24.4-linux.tgz
  # very verbose, blows log limit.
  - tar -xvf android-sdk_r24.4-linux.tgz > /dev/null 2>&1
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter platform-tools 
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter build-tools-26.0.0
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter android-25
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-android-support
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-android-m2repository
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-google-m2repository
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/26.0.0

script:
  # fix up java path.
  - echo ===== sb start script section =====
  - java -version
  - echo JAVA_HOME is $JAVA_HOME
  - export JAVA_HOME="/usr/lib/jvm/java-8-oracle"
  - echo JAVA_HOME is $JAVA_HOME
  - ls $JAVA_HOME
  - echo sb end java

  # list node versions.
  - echo ===== sb npm global dependencies =====
  - npm list -g --depth=0
  - echo ===== sb npm local dependencies =====
  - npm list --depth=0

  # list project specific versions.
  - ionic -v

  - mkdir www
  - ionic resources
  - cordova platform add android
  - ionic build android

after_success:
  - ./push.sh
